- name: Raydevs Server installation
  hosts: server
  gather_subset: env
  vars:
    ansible_ssh_private_key_file: /root/.ssh/aws.pem
  become: true
  tasks:
    - name: Install Server
      block:
        - name: Install PKGs
          apt:
            pkg:
              - nginx
              - docker.io
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
              - python3-pip
              - virtualenv
              - python3-setuptools
            state: latest
            update_cache: true
          become: true
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present

        - name: Update apt and install docker-ce
          apt:
            name: docker-ce
            state: latest
            update_cache: true
        - name: Install Docker Module for Python
          pip:
            name: docker
        - pip:
            name: docker-compose
      tags:
        - install
    - name: Update server
      block:
        - name: Close docker service
          community.general.docker_compose:
            project_src: /root
            state: absent
        - name: Pull and run docker service
          community.general.docker_compose:
            pull: true
            project_src: /root
            state: present
      tags:
        - update