version: "3"
services:
  client:
    platform: linux/amd64
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: ghcr.io/raygamedev/raydevsrs:client
    command: serve -s -l 3000 build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
