version: "3"
services:
  client:
    #platform: linux/amd64
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: ghcr.io/raygamedev/raydevsrs:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
